# Generated by Django 3.1.6 on 2021-02-07 14:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(max_length=50, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastname',
            field=models.CharField(max_length=50, null=True, verbose_name='Soyisim'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(verbose_name='Adres'),
        ),
    ]
